### ISSUE TITLE
As a user, I'd like to pull the library from a CDN

### ISSUE THREAD

**Issue by LabOfOz** [LabOfOz/seeclark#12]
Let's make it so that users can load seeclark.js from [unpkg](https://unpkg.com/).

### Tasks

- [ ] Add library to NPM
- [ ] Check that our library loads on unpkg
- [ ] Add links to CDN's in readme

**Comment by mastashake08** [comment]
Why are you using CDN instead of a build

**Comment by LabOfOz** [comment]
It'll have builds as well, but with a CDN I can test that this works on CodePen/JsFiddle. The other nice thing about CDN's is that you can just drop it into any HTML file to test it without setting up an environment
